# lucas gatsas Theme/Blog - Jekyll Theme
# the glas theme: https://github.com/SpaceG/glas
# Author: LucasGatsas
# Theme: glas
# Source: https://github.com/spaceg/glas
# Mail: space@lucasgatsas.ch
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Miju E. Han
#What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label: Art

description: > # "
  Miju E. Han is a data scientist and artist based in San Francisco, CA.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.lucasgatsas.ch" # the base hostname & protocol for your site

#These settings might be able to go?
author: Miju E. Han
twitter_username: mijuhan
github_username:  mijuhan
company_name: lucasgatsas

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /event/:title.html
